# Generated by Django 4.1.2 on 2022-10-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenity',
            new_name='Amenities',
        ),
    ]
